=== PDXostc/common-app/most/config.dtd
<!ELEMENT plugin-properties (library-name, feature-install-uri?,
  feature-key-cn?, feature-root-cn?,
  feature-root-fingerprint?, feature-set*, api-feature+) >

<!ELEMENT library-name (#PCDATA)>

<!ELEMENT feature-set (api-feature-ref+)>
<!ATTLIST feature-set name CDATA #REQUIRED >

<!ELEMENT api-feature-ref EMPTY>
<!ATTLIST api-feature-ref name CDATA #REQUIRED >

<!ELEMENT api-feature (name, device-capability*, Object*, Function*, Property* )>

<!ELEMENT name (#PCDATA) >
<!ELEMENT device-capability (#PCDATA )>

<!ELEMENT Object (Function*, Property*)>
<!ATTLIST Object name CDATA #REQUIRED >

<!ELEMENT Function (#PCDATA )>
<!ATTLIST Function name CDATA #REQUIRED >
<!ATTLIST Function restricted CDATA #IMPLIED >

<!ELEMENT Property (#PCDATA )>


<!ELEMENT feature-install-uri (#PCDATA)>
<!ELEMENT feature-key-cn (#PCDATA)>
<!ELEMENT feature-root-cn (#PCDATA)>
<!ELEMENT feature-root-fingerprint (#PCDATA)>

=== PDXostc/common-app/cameras_ext/src/config.xml
<?xml version="1.0" ?>
<!DOCTYPE plugin-properties SYSTEM "/usr/etc/tizen-apis/config.dtd">
<plugin-properties>
    <library-name>libwrt-plugins-tizen-cameras.so</library-name>
    <feature-install-uri>cameras.install.uri</feature-install-uri>
    <feature-key-cn>INTEL plugin group</feature-key-cn>
    <feature-root-cn>INTEL certificate authority</feature-root-cn>
    <feature-root-fingerprint>AAAABBBBCCCCDDDEEEE0000</feature-root-fingerprint>

    <api-feature>
        <name>http://tizen.org/privilege/cameras</name>
        <device-capability>cameras</device-capability>
    </api-feature>
                            
</plugin-properties>

=== PDXostc/common-app/most/src/config.xml
<?xml version="1.0" ?>
<!DOCTYPE plugin-properties SYSTEM "/usr/etc/tizen-apis/config.dtd">
<plugin-properties>
    <library-name>libwrt-plugins-tizen-most.so</library-name>
    <feature-install-uri>most.install.uri</feature-install-uri>
    <feature-key-cn>INTEL plugin group</feature-key-cn>
    <feature-root-cn>INTEL certificate authority</feature-root-cn>
    <feature-root-fingerprint>AAAABBBBCCCCDDDEEEE0000</feature-root-fingerprint>

    <api-feature>
        <name>http://tizen.org/privilege/most</name>
        <device-capability>most</device-capability>
    </api-feature>

                            
</plugin-properties>

=== PDXostc/common-app/most/example/src/config.xml
<?xml version="1.0" ?>
<!DOCTYPE plugin-properties SYSTEM "/usr/etc/tizen-apis/config.dtd">
<plugin-properties>
    <library-name>libwrt-plugins-tizen-example.so</library-name>
    <feature-install-uri>example.install.uri</feature-install-uri>
    <feature-key-cn>INTEL plugin group</feature-key-cn>
    <feature-root-cn>INTEL certificate authority</feature-root-cn>
    <feature-root-fingerprint>AAAABBBBCCCCDDDEEEE0000</feature-root-fingerprint>

    <api-feature>
        <name>http://tizen.org/privilege/example</name>
        <device-capability>example</device-capability>
    </api-feature>

                            
</plugin-properties>
